<a href="https://colab.research.google.com/github/zydanne-costa/Ondas_ADCP_SCO_Mar_Nov_2025/blob/main/Vento_ERA5_CHU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Caminhos


março /content/drive/MyDrive/Ondas/VENTO_ERA5/Vento_SCO_ERAS5_MAR_2025.csv


abril /content/drive/MyDrive/Ondas/VENTO_ERA5/Vento_SCO_ERAS5_ABR_2025.csv

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
# marco
file_path = '/content/drive/MyDrive/Ondas/VENTO_ERA5/Vento_SCO_ERAS5_MAR_2025.csv'
df_mar = pd.read_csv(file_path, sep=';')

# Display the first 5 rows of the DataFrame
display(df_mar.head())

,system:index,datetime,dir_deg,vel_m_s,.geo
0,20250301T00,01/03/2025 00:00,79.960901,5.473096,"{""type"":""MultiPoint"",""coordinates"":[]}"
1,20250301T01,01/03/2025 01:00,81.206401,5.199901,"{""type"":""MultiPoint"",""coordinates"":[]}"
2,20250301T02,01/03/2025 02:00,73.613345,4.770325,"{""type"":""MultiPoint"",""coordinates"":[]}"
3,20250301T03,01/03/2025 03:00,73.666036,5.350426,"{""type"":""MultiPoint"",""coordinates"":[]}"
4,20250301T04,01/03/2025 04:00,82.276695,5.835591,"{""type"":""MultiPoint"",""coordinates"":[]}"

In [ ]:
df_wind_mar = pd.Dataframe()
df_wind_mar['datetime'] = pd.todatetime(df_mar[datetime], format='%d/%m/%Y %H:%M')

In [ ]:
# Display the first 5
display(df_wind_mar.head())

In [ ]:
# abril
file_path = '/content/drive/MyDrive/Ondas/VENTO_ERA5/Vento_SCO_ERAS5_ABR_2025.csv'
df_abr = pd.read_csv(file_path, sep=';')

# Display the first 5 rows of the DataFrame
display(df_abr.head())

,system:index,datetime,dir_deg,vel_m_s,.geo
0,20250401T00,01/04/2025 00:00,36.379505,6.450548,"{""type"":""MultiPoint"",""coordinates"":[]}"
1,20250401T01,01/04/2025 01:00,34.414886,6.570108,"{""type"":""MultiPoint"",""coordinates"":[]}"
2,20250401T02,01/04/2025 02:00,35.730312,6.294644,"{""type"":""MultiPoint"",""coordinates"":[]}"
3,20250401T03,01/04/2025 03:00,32.120132,5.993272,"{""type"":""MultiPoint"",""coordinates"":[]}"
4,20250401T04,01/04/2025 04:00,30.733979,5.708288,"{""type"":""MultiPoint"",""coordinates"":[]}"